language: ruby
branches:
  only:
    - master
    - stable
rvm:
  - 1.9.2
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 1.9.2
env:
  global:
    RAILS_ENV='test'
before_install:
  - gem update bundler
install:
  - bundle install --without development
before_script:
  - bundle exec gem list
  - bundle exec rake dtf:install
  - bundle exec thor dtf_setup:install
script: bundle exec rspec spec --profile
after_script: RAILS_ENV='production' gem build dtf-session.gemspec
notifications:
  irc:
    channels:
        - "irc.freenode.org#pgpkeys"
    on_failure: always
    on_success: always
  email:
    recipients:
      - me@daviddwdowney.com
    on_failure: always
    on_success: always
